In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

In [18]:
cd D:\OneDrive\Lammps\nanoglass\20181116_800K_NPTb+800-300K_NPTb+300K_NVTb_xTen_E-2Aps\data_analyses_2\data_files

D:\OneDrive\Lammps\nanoglass\20181116_800K_NPTb+800-300K_NPTb+300K_NVTb_xTen_E-2Aps\data_analyses_2\data_files

In [19]:
temp =800
step = 0

estrain = step * 0.01 * 0.042
txt_name = 'ZrCuO_NG_%iK_%.3f_elemental distribution.txt'%(temp,estrain)
pd.DataFrame(pd.read_csv(txt_name,sep=',')).iloc[97:105]

        x_cor         Cu          O         Zr  number density
97   119.9890  36.363636  40.559441  23.076923        0.122806
98   121.1825  26.530612  55.782313  17.687075        0.126241
99   122.3755  21.875000  65.625000  12.500000        0.109924
100  123.5690  25.203252  60.162602  14.634146        0.105631
101  124.7625  30.882353  52.941176  16.176471        0.116795
102  125.9560  32.941176  43.529412  23.529412        0.145993
103  127.1495  43.225806  25.806452  30.967742        0.133112
104  128.3430  50.335570  20.805369  28.859060        0.127959

In [20]:
temp =800
step = 1200

estrain = step * 0.01 * 0.042
txt_name = 'ZrCuO_NG_%iK_%.3f_elemental distribution.txt'%(temp,estrain)
pd.DataFrame(pd.read_csv(txt_name,sep=',')).iloc[97:105]

        x_cor         Cu          O         Zr  number density
97   118.5535  50.000000  24.675325  25.324675        0.130633
98   120.3485  33.734940  44.578313  21.686747        0.140812
99   122.1435  27.027027  56.081081  16.891892        0.125543
100  123.9385  24.161074  55.033557  20.805369        0.126392
101  125.7335  28.025478  52.866242  19.108280        0.133178
102  127.5285  43.827160  30.246914  25.925926        0.137419
103  129.3235  49.681529  25.477707  24.840764        0.133178
104  131.1190  56.097561  12.195122  31.707317        0.139116